### ISSUE TITLE
mpv problem

### ISSUE THREAD

**Issue by tom2411** [karaokemugen/karaokemugen-app#27]
Hello, I tried to use the AppImage to try Karaoke Mugen but I have this message during the first launch :

```
21:15:01 - error: [mpv] Unable to get sound devices from mpv Error: Command failed with exit code 127: /tmp/.mount_Karaok8UwWn4/app/bin/mpv --audio-device=help
/tmp/.mount_Karaok8UwWn4/app/bin/mpv: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Error: Command failed with exit code 127: /tmp/.mount_Karaok8UwWn4/app/bin/mpv --audio-device=help
/tmp/.mount_Karaok8UwWn4/app/bin/mpv: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/tmp/.mount_Karaok8UwWn4/resources/app.asar/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/tmp/.mount_Karaok8UwWn4/resources/app.asar/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getMpvAudioOutputs (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:311:18)
    at _Players.initPlayerSystem (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:940:24)
    at initPlayer (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/services/player.ts:350:3)
    at /tmp/.mount_Karaok8UwWn4/resources/app.asar/src/controllers/frontend/player.ts:66:5
    at SocketIOApp.routeRequest (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/lib/utils/ws.ts:57:34)
    at Socket8.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/lib/utils/ws.ts:86:17)
21:15:01 - warn:  [mpv] Unable to determine mpv version. Will assume this is a recent one Error: Command failed with exit code 127: /tmp/.mount_Karaok8UwWn4/app/bin/mpv --version
/tmp/.mount_Karaok8UwWn4/app/bin/mpv: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Error: Command failed with exit code 127: /tmp/.mount_Karaok8UwWn4/app/bin/mpv --version
/tmp/.mount_Karaok8UwWn4/app/bin/mpv: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/tmp/.mount_Karaok8UwWn4/resources/app.asar/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/tmp/.mount_Karaok8UwWn4/resources/app.asar/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at checkMpv (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:331:18)
    at Object.bootstrapPlayers (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:922:3)
    at _Players.initPlayerSystem (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:947:4)
    at initPlayer (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/services/player.ts:350:3)
    at /tmp/.mount_Karaok8UwWn4/resources/app.asar/src/controllers/frontend/player.ts:66:5
    at SocketIOApp.routeRequest (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/lib/utils/ws.ts:57:34)
    at Socket8.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/lib/utils/ws.ts:86:17)
21:15:01 - warn:  [mpv] Failed to start mpv, attempt 1, trying 3 more times... Error: Mpv process exited with 127
Error: Mpv process exited with 127
    at ChildProcess.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/utils/mpvIPC.ts:53:28)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
21:15:02 - warn:  [mpv] Failed to start mpv, attempt 2, trying 2 more times... Error: Mpv process exited with 127
Error: Mpv process exited with 127
    at ChildProcess.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/utils/mpvIPC.ts:53:28)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
21:15:04 - warn:  [mpv] Failed to start mpv, attempt 3, trying 1 more times... Error: Mpv process exited with 127
Error: Mpv process exited with 127
    at ChildProcess.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/utils/mpvIPC.ts:53:28)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
21:15:08 - warn:  [mpv] Failed to start mpv, attempt 4, trying 0 more times... Error: Mpv process exited with 127
Error: Mpv process exited with 127
    at ChildProcess.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/utils/mpvIPC.ts:53:28)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
21:15:08 - error: [mpv] Cannot start MPV Error: Mpv process exited with 127
Error: Mpv process exited with 127
    at ChildProcess.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/utils/mpvIPC.ts:53:28)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
21:15:08 - error: [mpv] mpvAPI (send) Error: Mpv process exited with 127
Error: Mpv process exited with 127
    at ChildProcess.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/utils/mpvIPC.ts:53:28)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
21:15:08 - error: [mpv] Unable to get mpv log Error: ENOENT: no such file or directory, open '/home/tom/KaraokeMugen/logs/mpv.log'
Error: ENOENT: no such file or directory, open '/home/tom/KaraokeMugen/logs/mpv.log'
21:15:08 - error: [mpv] Unable to start player Error: {"attemptNumber":4,"retriesLeft":0}
Error: {"attemptNumber":4,"retriesLeft":0}
    at Object.exec (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:828:10)
    at Object.bootstrapPlayers (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:930:3)
    at _Players.initPlayerSystem (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:947:4)
    at initPlayer (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/services/player.ts:350:3)
    at /tmp/.mount_Karaok8UwWn4/resources/app.asar/src/controllers/frontend/player.ts:66:5
    at SocketIOApp.routeRequest (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/lib/utils/ws.ts:57:34)
    at Socket8.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/lib/utils/ws.ts:86:17)
21:15:08 - error: [Player] Failed mpv init Error: {"attemptNumber":4,"retriesLeft":0}
Error: {"attemptNumber":4,"retriesLeft":0}
    at Object.exec (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:828:10)
    at Object.bootstrapPlayers (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:930:3)
    at _Players.initPlayerSystem (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/components/mpv.ts:947:4)
    at initPlayer (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/services/player.ts:350:3)
    at /tmp/.mount_Karaok8UwWn4/resources/app.asar/src/controllers/frontend/player.ts:66:5
    at SocketIOApp.routeRequest (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/lib/utils/ws.ts:57:34)
    at Socket8.<anonymous> (/tmp/.mount_Karaok8UwWn4/resources/app.asar/src/lib/utils/ws.ts:86:17)
```

And after a little time the app launch normally. 
But on the second launch the app crash saying that there is a problem with mpv, so i tried what is written in the doc :
```
sudo add-apt-repository ppa:mc3man/mpv-tests
sudo apt-get update
sudo apt-get install mpv
```

but when I try, I have this : 
```
Appuyez sur [ENTRÉE] pour continuer ou Ctrl-c pour annuler
Adding deb entry to /etc/apt/sources.list.d/mc3man-ubuntu-mpv-tests-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/mc3man-ubuntu-mpv-tests-jammy.list
Adding key to /etc/apt/trusted.gpg.d/mc3man-ubuntu-mpv-tests.gpg with fingerprint 8E51A6D660CD88D67D65221D90BD7EACED8E640A
Atteint :1 http://fr.archive.ubuntu.com/ubuntu jammy InRelease
Atteint :2 http://fr.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                           
Atteint :3 http://fr.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                         
Ign :4 https://ppa.launchpadcontent.net/mc3man/mpv-tests/ubuntu jammy InRelease                                                  
Réception de :5 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Err :6 https://ppa.launchpadcontent.net/mc3man/mpv-tests/ubuntu jammy Release
  404  Not Found [IP : 2620:2d:4000:1::3e 443]
Lecture des listes de paquets... Fait
E: Le dépôt https://ppa.launchpadcontent.net/mc3man/mpv-tests/ubuntu jammy Release n'a pas de fichier Release.
N: Les mises à jour depuis un tel dépôt ne peuvent s'effectuer de manière sécurisée, et sont donc désactivées par défaut.
N: Voir les pages de manuel d'apt-secure(8) pour la création des dépôts et les détails de configuration d'un utilisateur.
```

Thank you

**Comment by AxelTerizaki** [comment]
Hello, and thanks for writing an issue. 

I must have forgotten to disable them on github though, as technically our main repository is on gitlab here : https://gitlab.com/karaokemugen/karaokemugen-app

For your specific problem, since you opened it here though, I'll answer it.

We ship a mpv binary that might lack some libraries. We're trying still to pinpoint which but ti might differ on every distribution.

I see an issue with the Ubuntu PPA you added, and I can't help with that. You can add mpv and have KM use the system's one instead of the one we shipped, but it requires modifying the config file in `~/KaraokeMugen`

A simpler solution though would be to try our master release instead of the stable one. The master release is close to stable but there's one feature we still want to add that's not yet done, but it's totally fine.

https://mugen.karaokes.moe/download.html

You'll find the `master` release which should be 7.0.33 at the moment, you can safely use it instead of version 6. Note that once the database has been migrated to 7.x you won't be able to use 6.x anymore on your system.
